# Prepare a build-local archive, never mutate the FFmpeg installation.
# Rename only the defining object: decoder callers must still reach our wrapper.
foreach(required INPUT_ARCHIVE OUTPUT_ARCHIVE AR OBJCOPY NM)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
if(INPUT_ARCHIVE STREQUAL OUTPUT_ARCHIVE)
    message(FATAL_ERROR "Input and output archives must differ")
endif()
set(work_dir "${OUTPUT_ARCHIVE}.work")
file(MAKE_DIRECTORY "${work_dir}")
function(run_checked)
    execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${work_dir}"
        RESULT_VARIABLE result ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Archive hook failed: ${ARGV}: ${error}")
    endif()
endfunction()
run_checked("${AR}" x "${INPUT_ARCHIVE}" h264qpel.o)
execute_process(COMMAND "${NM}" --defined-only "${work_dir}/h264qpel.o"
    RESULT_VARIABLE result OUTPUT_VARIABLE symbols ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot inspect h264qpel.o: ${error}")
endif()
if(symbols MATCHES "[ \t][Tt][ \t]+ff_h264qpel_init([\r\n]|$)")
    run_checked("${OBJCOPY}" --dump-section ".text=before.text" h264qpel.o)
    run_checked("${OBJCOPY}" --redefine-sym
        ff_h264qpel_init=nuvio_baseline_h264qpel_init h264qpel.o)
    run_checked("${OBJCOPY}" --dump-section ".text=after.text" h264qpel.o)
    file(SHA256 "${work_dir}/before.text" before)
    file(SHA256 "${work_dir}/after.text" after)
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "Archive hook changed original initializer machine code")
    endif()
elseif(NOT symbols MATCHES "[ \t][Tt][ \t]+nuvio_baseline_h264qpel_init([\r\n]|$)")
    message(FATAL_ERROR "Expected FFmpeg 7.0.2 qpel initializer absent")
endif()
configure_file("${INPUT_ARCHIVE}" "${OUTPUT_ARCHIVE}" COPYONLY)
run_checked("${AR}" r "${OUTPUT_ARCHIVE}" h264qpel.o)
