package com.nuvio.tv.data.trailer

data class TrailerPlaybackSource(
    val videoUrl: String,
    val audioUrl: String? = null
)

data class TrailerSubtitleTrack(
    val languageCode: String,
    val url: String,
    val isAutoGenerated: Boolean
)
