cmake_minimum_required(VERSION 3.21)
project(nuvio_iamf C CXX)
set(CMAKE_CXX_STANDARD 11)
add_subdirectory("${IAMF_SOURCE}/code" libiamf EXCLUDE_FROM_ALL)
add_library(iamfJNI SHARED "${MEDIA_SOURCE}/libraries/decoder_iamf/src/main/jni/iamf_jni.cc")
target_include_directories(iamfJNI PRIVATE "${IAMF_SOURCE}/code/include")
target_link_libraries(iamfJNI PRIVATE android iamf log)
target_link_options(iamf PRIVATE "-Wl,-z,max-page-size=16384")
target_link_options(iamfJNI PRIVATE "-Wl,-z,max-page-size=16384")
